# ═══════════════════════════════════════════════════════════════════════════════
# custom-domain.yml - Add Custom Domain Workflow
# ═══════════════════════════════════════════════════════════════════════════════
#
# Manually add a custom domain to an app.
# This workflow:
#   1. Adds the domain to the app
#   2. Generates Let's Encrypt certificate
#   3. Provides DNS instructions
#
# ═══════════════════════════════════════════════════════════════════════════════

name: Add Custom Domain

on:
  workflow_dispatch:
    inputs:
      app_name:
        description: 'Dokku app name'
        required: true
        type: string
      custom_domain:
        description: 'Custom domain (e.g., www.example.com)'
        required: true
        type: string
      setup_ssl:
        description: 'Enable SSL (Let''s Encrypt)'
        required: true
        default: true
        type: boolean

jobs:
  add-domain:
    name: Add Custom Domain
    runs-on: ubuntu-latest

    steps:
      - name: Validate domain format
        run: |
          DOMAIN="${{ github.event.inputs.custom_domain }}"

          # Basic domain validation
          if ! echo "$DOMAIN" | grep -qE "^[a-zA-Z0-9]([a-zA-Z0-9-]*[a-zA-Z0-9])?(\.[a-zA-Z0-9]([a-zA-Z0-9-]*[a-zA-Z0-9])?)*\.[a-zA-Z]{2,}$"; then
            echo "❌ Invalid domain format: $DOMAIN"
            exit 1
          fi

          echo "✅ Domain format valid: $DOMAIN"

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DOKKU_SSH_PRIVATE_KEY }}" > ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key
          ssh-keyscan -H ${{ secrets.DOKKU_HOST }} >> ~/.ssh/known_hosts 2>/dev/null

      - name: Check app exists
        run: |
          if ! ssh -i ~/.ssh/deploy_key dokku@${{ secrets.DOKKU_HOST }} \
            apps:exists ${{ github.event.inputs.app_name }} 2>/dev/null; then
            echo "❌ App not found: ${{ github.event.inputs.app_name }}"
            exit 1
          fi
          echo "✅ App exists: ${{ github.event.inputs.app_name }}"

      - name: Display DNS instructions
        run: |
          SERVER_IP=$(ssh -i ~/.ssh/deploy_key dokku@${{ secrets.DOKKU_HOST }} \
            'curl -s ifconfig.me' 2>/dev/null || echo "YOUR_SERVER_IP")

          echo ""
          echo "═══════════════════════════════════════════════════════════════"
          echo "  DNS CONFIGURATION REQUIRED"
          echo "═══════════════════════════════════════════════════════════════"
          echo ""
          echo "Before SSL can be enabled, configure DNS for your domain:"
          echo ""
          echo "Option 1 - CNAME record (recommended for subdomains):"
          echo "  Type:  CNAME"
          echo "  Name:  ${{ github.event.inputs.custom_domain }}"
          echo "  Value: ${{ github.event.inputs.app_name }}.${{ secrets.BASE_DOMAIN }}"
          echo ""
          echo "Option 2 - A record (required for apex/root domains):"
          echo "  Type:  A"
          echo "  Name:  ${{ github.event.inputs.custom_domain }}"
          echo "  Value: $SERVER_IP"
          echo ""
          echo "═══════════════════════════════════════════════════════════════"

      - name: Add domain to app
        run: |
          echo "Adding domain ${{ github.event.inputs.custom_domain }} to ${{ github.event.inputs.app_name }}..."

          ssh -i ~/.ssh/deploy_key dokku@${{ secrets.DOKKU_HOST }} \
            domains:add ${{ github.event.inputs.app_name }} ${{ github.event.inputs.custom_domain }}

          echo "✅ Domain added"

      - name: Check DNS propagation
        id: dns_check
        continue-on-error: true
        run: |
          DOMAIN="${{ github.event.inputs.custom_domain }}"
          echo "Checking DNS propagation for $DOMAIN..."

          # Try to resolve the domain
          RESOLVED=$(dig +short "$DOMAIN" 2>/dev/null | head -1)

          if [ -n "$RESOLVED" ]; then
            echo "✅ DNS resolves to: $RESOLVED"
            echo "dns_ready=true" >> $GITHUB_OUTPUT
          else
            echo "⚠️ DNS not yet propagated"
            echo "dns_ready=false" >> $GITHUB_OUTPUT
          fi

      - name: Generate SSL certificate
        if: github.event.inputs.setup_ssl == 'true'
        run: |
          echo "Generating SSL certificate..."

          # Try to enable Let's Encrypt
          if ssh -i ~/.ssh/deploy_key dokku@${{ secrets.DOKKU_HOST }} \
            letsencrypt:enable ${{ github.event.inputs.app_name }} 2>&1; then
            echo "✅ SSL certificate generated"
          else
            echo "⚠️ SSL generation failed - DNS may not be propagated yet"
            echo ""
            echo "To manually enable SSL later, run:"
            echo "  ssh dokku@${{ secrets.DOKKU_HOST }} letsencrypt:enable ${{ github.event.inputs.app_name }}"
          fi

      - name: Show current domains
        run: |
          echo ""
          echo "Current domains for ${{ github.event.inputs.app_name }}:"
          ssh -i ~/.ssh/deploy_key dokku@${{ secrets.DOKKU_HOST }} \
            domains:report ${{ github.event.inputs.app_name }}

      - name: Summary
        run: |
          echo ""
          echo "═══════════════════════════════════════════════════════════════"
          echo "  SETUP COMPLETE"
          echo "═══════════════════════════════════════════════════════════════"
          echo ""
          echo "App: ${{ github.event.inputs.app_name }}"
          echo "Domain: ${{ github.event.inputs.custom_domain }}"
          echo "URL: https://${{ github.event.inputs.custom_domain }}"
          echo ""
          echo "If SSL failed, wait for DNS propagation and run:"
          echo "  ssh dokku@${{ secrets.DOKKU_HOST }} letsencrypt:enable ${{ github.event.inputs.app_name }}"
          echo ""
